apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: htem
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: htem
    app.kubernetes.io/part-of: byoc-app-ynsx
  name: htem
spec:
  rules:
  - host: htem-byoc-czrt-tenant.apps.d40181603f2d9db32ab9.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: htem
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
